name: autotest

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  autotest:
    runs-on: macos-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Get Environment Cache
        id: environment-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/node
            /usr/local/bin/node
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/bin/depsync
            /usr/local/lib/node_modules/depsync
            /usr/local/Cellar/gcovr
            /usr/local/bin/gcovr
            /usr/local/bin/clang-format
          key: tgfx-environment-autotest-20231022

      - name: Get Third-Party Cache
        id: third-party-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            third_party
            vendor_tools
            test/baseline/.cache
          key: third_party-autotest-01-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}
          restore-keys: third_party-autotest-

      - name: Check Code Format
        run: |
          chmod +x codeformat.sh
          ./codeformat.sh
        shell: bash

      - name: Run sync_deps script
        run: |
          chmod +x sync_deps.sh
          ./sync_deps.sh
        shell: bash

      - name: Build Third-Party cache
        if: github.event_name == 'push'
        run: |
          node build_vendor -p mac
          chmod +x update_baseline.sh
          ./update_baseline.sh 1

      - name: Run Autotest
        if: github.event_name == 'pull_request'
        run: |
          chmod +x autotest.sh
          ./autotest.sh

      - name: Update Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: result/coverage.xml

      - name: Save Environment Cache
        if: ${{ (github.event_name == 'push') && (steps.environment-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v3
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/Cellar/icu4c
            /usr/local/bin/ninja
            /usr/local/Cellar/node
            /usr/local/bin/node
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/bin/depsync
            /usr/local/lib/node_modules/depsync
            /usr/local/Cellar/gcovr
            /usr/local/bin/gcovr
            /usr/local/bin/clang-format
          key: tgfx-environment-autotest-20231022

      - name: Save Third-Party Cache
        if: ${{ (github.event_name == 'push') && (steps.third-party-cache.outputs.cache-hit != 'true') }}
        uses: actions/cache/save@v3
        with:
          path: |
            third_party
            vendor_tools
            test/baseline/.cache
          key: third_party-autotest-01-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}-${{ hashFiles('test/baseline/version.json') }}

      - name: Job Failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result
